/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for defining updates and subscriptions to parts of a SignalK data model, for example for communicating updates of data
 */
export interface SignalKDeltaMessageSchema {
  /**
   * The context path of the updates, eg. the top level path plus object identifier.
   */
  context?: string;
  /**
   * The updates
   */
  updates: (
    | {
        $source?: unknown;
        source?: unknown;
        timestamp?: unknown;
        values: unknown;
      }
    | {
        $source?: unknown;
        source?: unknown;
        timestamp?: unknown;
        meta: unknown;
      }
    | {
        $source?: unknown;
        source?: unknown;
        timestamp?: unknown;
        values: unknown;
        meta: unknown;
      }
  )[];
  [k: string]: unknown;
}
